/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TxId = IDL.Nat;
export const Amount = IDL.Nat;
export const PaymentMethodType = IDL.Variant({
  'bank' : IDL.Null,
  'card' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Currency = IDL.Variant({
  'AUD' : IDL.Null,
  'CAD' : IDL.Null,
  'EUR' : IDL.Null,
  'GBP' : IDL.Null,
  'JPY' : IDL.Null,
  'USD' : IDL.Null,
});
export const StripePaymentResult = IDL.Record({
  'amount_charged' : Amount,
  'error_message' : IDL.Opt(IDL.Text),
  'currency' : Currency,
  'charge_id' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const VerificationStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Unverified' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Record({
  'id' : IDL.Nat,
  'token' : IDL.Text,
  'last4' : IDL.Text,
  'stripe_payment_method_id' : IDL.Opt(IDL.Text),
  'verification_status' : VerificationStatus,
  'displayLabel' : IDL.Text,
  'isDefault' : IDL.Bool,
  'pmType' : PaymentMethodType,
  'expiry' : IDL.Text,
  'account_holder_name' : IDL.Opt(IDL.Text),
});
export const CurrencyAmount = IDL.Record({
  'currency' : Currency,
  'amount' : Amount,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SavingsCategory = IDL.Variant({
  'Car' : IDL.Null,
  'Home' : IDL.Null,
  'Custom' : IDL.Null,
  'Vacation' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const StripeSetupIntent = IDL.Record({
  'payment_method_id' : IDL.Opt(IDL.Text),
  'client_secret' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'free' : IDL.Null,
  'plus' : IDL.Null,
  'business' : IDL.Null,
});
export const BillingInterval = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const CardControl = IDL.Record({
  'isFrozen' : IDL.Bool,
  'internationalEnabled' : IDL.Bool,
  'paymentMethodId' : IDL.Text,
  'hasVirtualCard' : IDL.Bool,
  'onlineEnabled' : IDL.Bool,
  'virtualCardLast4' : IDL.Opt(IDL.Text),
  'virtualCardExpiry' : IDL.Opt(IDL.Text),
  'maxTransactionLimit' : IDL.Opt(IDL.Nat),
});
export const ActivityType = IDL.Variant({
  'JoinedViaInvite' : IDL.Null,
  'Sent' : IDL.Null,
  'Achievement' : IDL.Null,
  'Received' : IDL.Null,
  'SavingsGoal' : IDL.Null,
});
export const ReactionEntry = IDL.Record({
  'by' : IDL.Vec(IDL.Principal),
  'emoji' : IDL.Text,
});
export const ActivityItem = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Opt(IDL.Text),
  'actionType' : ActivityType,
  'actorUsername' : IDL.Text,
  'currency' : IDL.Opt(Currency),
  'timestamp' : Timestamp,
  'actorPrincipal' : IDL.Principal,
  'isPublic' : IDL.Bool,
  'amount' : IDL.Opt(IDL.Nat),
  'reactions' : IDL.Vec(ReactionEntry),
});
export const AutoPayConfig = IDL.Record({
  'defaultPayoutMethodId' : IDL.Opt(IDL.Text),
  'autoDepositOnReceive' : IDL.Bool,
  'autoChargeOnSend' : IDL.Bool,
});
export const SpendingCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Bills' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Shopping' : IDL.Null,
  'Other' : IDL.Null,
  'Transfers' : IDL.Null,
  'Transport' : IDL.Null,
});
export const BudgetSetting = IDL.Record({
  'limitCents' : IDL.Nat,
  'alertThreshold' : IDL.Nat,
  'category' : SpendingCategory,
});
export const DeviceSession = IDL.Record({
  'os' : IDL.Text,
  'session_id' : IDL.Text,
  'device_name' : IDL.Text,
  'last_active' : Timestamp,
  'is_current' : IDL.Bool,
  'ip_address' : IDL.Text,
});
export const FxRate = IDL.Record({
  'rate' : IDL.Float64,
  'to_currency' : Currency,
  'from_currency' : Currency,
  'fetched_at' : Timestamp,
});
export const InviteStats = IDL.Record({
  'redeemerUsernames' : IDL.Vec(IDL.Text),
  'redemptionCount' : IDL.Nat,
  'code' : IDL.Text,
});
export const NotifType = IDL.Variant({
  'System' : IDL.Null,
  'Security' : IDL.Null,
  'Promo' : IDL.Null,
  'Alert' : IDL.Null,
  'Payment' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notifType' : NotifType,
  'body' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Timestamp,
  'relatedTxId' : IDL.Opt(TxId),
});
export const TxStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const MoneyRequest = IDL.Record({
  'id' : TxId,
  'status' : TxStatus,
  'requester' : IDL.Principal,
  'note' : IDL.Text,
  'currency' : Currency,
  'timestamp' : Timestamp,
  'payer' : IDL.Principal,
  'amount' : Amount,
});
export const ReferralRewardRecord = IDL.Record({
  'inviteCode' : IDL.Text,
  'amount' : IDL.Nat,
  'paidAt' : IDL.Int,
});
export const ReferralRewardSummary = IDL.Record({
  'pendingRewards' : IDL.Nat,
  'totalEarned' : IDL.Nat,
  'paidRewards' : IDL.Vec(ReferralRewardRecord),
});
export const SavingsGoal = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'targetAmount' : IDL.Nat,
  'targetDate' : IDL.Opt(Timestamp),
  'category' : SavingsCategory,
  'isLocked' : IDL.Bool,
  'currentAmount' : IDL.Nat,
  'autoDepositInterval' : IDL.Opt(IDL.Text),
  'autoDepositAmount' : IDL.Opt(IDL.Nat),
});
export const CategoryBreakdown = IDL.Record({
  'total' : IDL.Nat,
  'count' : IDL.Nat,
  'category' : SpendingCategory,
});
export const AnalyticsSummary = IDL.Record({
  'totalSpent' : IDL.Nat,
  'avgTransaction' : IDL.Nat,
  'byCategory' : IDL.Vec(CategoryBreakdown),
  'biggestPurchase' : IDL.Nat,
  'monthOverMonth' : IDL.Int,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'trialing' : IDL.Null,
});
export const Subscription = IDL.Record({
  'status' : SubscriptionStatus,
  'interval' : BillingInterval,
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'tier' : SubscriptionTier,
  'currentPeriodEnd' : IDL.Int,
});
export const TxType = IDL.Variant({
  'request' : IDL.Null,
  'sent' : IDL.Null,
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'received' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TxId,
  'status' : TxStatus,
  'requestId' : IDL.Opt(TxId),
  'tax_amount' : Amount,
  'original_amount' : IDL.Opt(Amount),
  'note' : IDL.Text,
  'counterparty' : IDL.Opt(IDL.Principal),
  'currency' : Currency,
  'original_currency' : IDL.Opt(Currency),
  'timestamp' : Timestamp,
  'tax_rate' : IDL.Nat,
  'txType' : TxType,
  'base_amount' : Amount,
  'amount' : Amount,
});
export const TxMetadata = IDL.Record({
  'note' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'txId' : TxId,
});
export const TrustedContact = IDL.Record({
  'id' : IDL.Nat,
  'accessLevel' : IDL.Text,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'addedAt' : Timestamp,
  'phone' : IDL.Opt(IDL.Text),
});
export const NumberFormat = IDL.Variant({
  'Period' : IDL.Null,
  'Comma' : IDL.Null,
});
export const TxHistoryVisibility = IDL.Variant({
  'FriendsOnly' : IDL.Null,
  'Private' : IDL.Null,
  'Public' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'primary_currency' : Currency,
  'data_sharing' : IDL.Bool,
  'per_tx_limit' : Amount,
  'decimal_places' : IDL.Nat,
  'notification_promotions' : IDL.Bool,
  'notification_p2p_requests' : IDL.Bool,
  'number_format' : NumberFormat,
  'monthly_limit' : Amount,
  'notification_email_receipts' : IDL.Bool,
  'tx_history_visibility' : TxHistoryVisibility,
  'notification_payment_alerts' : IDL.Bool,
  'daily_limit' : Amount,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptMoneyRequest' : IDL.Func([TxId], [], []),
  'addFunds' : IDL.Func([Amount], [], []),
  'addPaymentMethod' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, PaymentMethodType, IDL.Text],
      [],
      [],
    ),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'addTrustedContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'autoDepositOnReceive' : IDL.Func(
      [TxId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'cancelSubscription' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'chargeCard' : IDL.Func(
      [IDL.Text, Amount, Currency],
      [StripePaymentResult],
      [],
    ),
  'confirmStripePaymentMethod' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PaymentMethodType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [PaymentMethod],
      [],
    ),
  'convertCurrency' : IDL.Func(
      [Amount, Currency, Currency],
      [CurrencyAmount],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInviteCode' : IDL.Func([], [IDL.Text], []),
  'createSavingsGoal' : IDL.Func(
      [IDL.Text, SavingsCategory, IDL.Nat, IDL.Opt(Timestamp)],
      [],
      [],
    ),
  'createStripeSetupIntent' : IDL.Func([], [StripeSetupIntent], []),
  'createSubscriptionCheckout' : IDL.Func(
      [SubscriptionTier, BillingInterval],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'depositToGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'exportTransactionsCsv' : IDL.Func([], [IDL.Text], []),
  'findUser' : IDL.Func(
      [
        IDL.Variant({
          'username' : IDL.Text,
          'email' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'findUserByIdOrUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'freezeCard' : IDL.Func([IDL.Text], [], []),
  'fxTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'generateVirtualCard' : IDL.Func([IDL.Text], [CardControl], []),
  'getActivityFeed' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ActivityItem)],
      ['query'],
    ),
  'getAutoPayConfig' : IDL.Func([], [AutoPayConfig], ['query']),
  'getBalance' : IDL.Func([], [Amount], ['query']),
  'getBudgets' : IDL.Func([], [IDL.Vec(BudgetSetting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCardControls' : IDL.Func([IDL.Text], [CardControl], ['query']),
  'getCurrencySymbol' : IDL.Func([Currency], [IDL.Text], ['query']),
  'getDeviceSessions' : IDL.Func([], [IDL.Vec(DeviceSession)], []),
  'getExchangeRate' : IDL.Func([Currency, Currency], [FxRate], []),
  'getInviteCode' : IDL.Func([], [IDL.Text], []),
  'getInviteStats' : IDL.Func([], [InviteStats], ['query']),
  'getMultiCurrencyBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Currency, Amount))],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
  'getReferralRewards' : IDL.Func([], [ReferralRewardSummary], ['query']),
  'getSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'getSpendingAnalytics' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [AnalyticsSummary],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Opt(TxType)],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionMetadata' : IDL.Func([TxId], [TxMetadata], ['query']),
  'getTrustedContacts' : IDL.Func([], [IDL.Vec(TrustedContact)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [UserSettings], []),
  'initiateWithdrawal' : IDL.Func(
      [IDL.Text, Amount, Currency],
      [StripePaymentResult],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isTwilioConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'lockGoal' : IDL.Func([IDL.Nat], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'redeemInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'rejectMoneyRequest' : IDL.Func([TxId], [], []),
  'removePaymentMethod' : IDL.Func([IDL.Nat], [], []),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'removeTrustedContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reportCardLostStolen' : IDL.Func([IDL.Text], [], []),
  'requestMoney' : IDL.Func([IDL.Principal, Amount, IDL.Text], [], []),
  'requestPhoneVerification' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'revokeAllSessions' : IDL.Func([], [], []),
  'revokeDeviceSession' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMoney' : IDL.Func([IDL.Principal, Amount, IDL.Text], [], []),
  'setBudget' : IDL.Func([SpendingCategory, IDL.Nat, IDL.Nat], [], []),
  'setCardControls' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'setDefaultPaymentMethod' : IDL.Func([IDL.Nat], [], []),
  'setGoalAutoDeposit' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([IDL.Text], [], []),
  'setTransactionCategory' : IDL.Func([TxId, SpendingCategory], [], []),
  'setTransactionNote' : IDL.Func([TxId, IDL.Text], [], []),
  'setTransactionTags' : IDL.Func([TxId, IDL.Vec(IDL.Text)], [], []),
  'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'togglePaymentVisibility' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'twilioTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfreezeCard' : IDL.Func([IDL.Text], [], []),
  'unlinkPhone' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateAutoPayConfig' : IDL.Func(
      [AutoPayConfig],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateProfilePhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateTrustedContact' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateUserSettings' : IDL.Func([UserSettings], [], []),
  'upsertSubscription' : IDL.Func([Subscription], [], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'withdrawFromGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'withdrawFunds' : IDL.Func([Amount], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TxId = IDL.Nat;
  const Amount = IDL.Nat;
  const PaymentMethodType = IDL.Variant({
    'bank' : IDL.Null,
    'card' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Currency = IDL.Variant({
    'AUD' : IDL.Null,
    'CAD' : IDL.Null,
    'EUR' : IDL.Null,
    'GBP' : IDL.Null,
    'JPY' : IDL.Null,
    'USD' : IDL.Null,
  });
  const StripePaymentResult = IDL.Record({
    'amount_charged' : Amount,
    'error_message' : IDL.Opt(IDL.Text),
    'currency' : Currency,
    'charge_id' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const VerificationStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Unverified' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Record({
    'id' : IDL.Nat,
    'token' : IDL.Text,
    'last4' : IDL.Text,
    'stripe_payment_method_id' : IDL.Opt(IDL.Text),
    'verification_status' : VerificationStatus,
    'displayLabel' : IDL.Text,
    'isDefault' : IDL.Bool,
    'pmType' : PaymentMethodType,
    'expiry' : IDL.Text,
    'account_holder_name' : IDL.Opt(IDL.Text),
  });
  const CurrencyAmount = IDL.Record({
    'currency' : Currency,
    'amount' : Amount,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SavingsCategory = IDL.Variant({
    'Car' : IDL.Null,
    'Home' : IDL.Null,
    'Custom' : IDL.Null,
    'Vacation' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const StripeSetupIntent = IDL.Record({
    'payment_method_id' : IDL.Opt(IDL.Text),
    'client_secret' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'free' : IDL.Null,
    'plus' : IDL.Null,
    'business' : IDL.Null,
  });
  const BillingInterval = IDL.Variant({
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const CardControl = IDL.Record({
    'isFrozen' : IDL.Bool,
    'internationalEnabled' : IDL.Bool,
    'paymentMethodId' : IDL.Text,
    'hasVirtualCard' : IDL.Bool,
    'onlineEnabled' : IDL.Bool,
    'virtualCardLast4' : IDL.Opt(IDL.Text),
    'virtualCardExpiry' : IDL.Opt(IDL.Text),
    'maxTransactionLimit' : IDL.Opt(IDL.Nat),
  });
  const ActivityType = IDL.Variant({
    'JoinedViaInvite' : IDL.Null,
    'Sent' : IDL.Null,
    'Achievement' : IDL.Null,
    'Received' : IDL.Null,
    'SavingsGoal' : IDL.Null,
  });
  const ReactionEntry = IDL.Record({
    'by' : IDL.Vec(IDL.Principal),
    'emoji' : IDL.Text,
  });
  const ActivityItem = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Opt(IDL.Text),
    'actionType' : ActivityType,
    'actorUsername' : IDL.Text,
    'currency' : IDL.Opt(Currency),
    'timestamp' : Timestamp,
    'actorPrincipal' : IDL.Principal,
    'isPublic' : IDL.Bool,
    'amount' : IDL.Opt(IDL.Nat),
    'reactions' : IDL.Vec(ReactionEntry),
  });
  const AutoPayConfig = IDL.Record({
    'defaultPayoutMethodId' : IDL.Opt(IDL.Text),
    'autoDepositOnReceive' : IDL.Bool,
    'autoChargeOnSend' : IDL.Bool,
  });
  const SpendingCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Bills' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Shopping' : IDL.Null,
    'Other' : IDL.Null,
    'Transfers' : IDL.Null,
    'Transport' : IDL.Null,
  });
  const BudgetSetting = IDL.Record({
    'limitCents' : IDL.Nat,
    'alertThreshold' : IDL.Nat,
    'category' : SpendingCategory,
  });
  const DeviceSession = IDL.Record({
    'os' : IDL.Text,
    'session_id' : IDL.Text,
    'device_name' : IDL.Text,
    'last_active' : Timestamp,
    'is_current' : IDL.Bool,
    'ip_address' : IDL.Text,
  });
  const FxRate = IDL.Record({
    'rate' : IDL.Float64,
    'to_currency' : Currency,
    'from_currency' : Currency,
    'fetched_at' : Timestamp,
  });
  const InviteStats = IDL.Record({
    'redeemerUsernames' : IDL.Vec(IDL.Text),
    'redemptionCount' : IDL.Nat,
    'code' : IDL.Text,
  });
  const NotifType = IDL.Variant({
    'System' : IDL.Null,
    'Security' : IDL.Null,
    'Promo' : IDL.Null,
    'Alert' : IDL.Null,
    'Payment' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notifType' : NotifType,
    'body' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Timestamp,
    'relatedTxId' : IDL.Opt(TxId),
  });
  const TxStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const MoneyRequest = IDL.Record({
    'id' : TxId,
    'status' : TxStatus,
    'requester' : IDL.Principal,
    'note' : IDL.Text,
    'currency' : Currency,
    'timestamp' : Timestamp,
    'payer' : IDL.Principal,
    'amount' : Amount,
  });
  const ReferralRewardRecord = IDL.Record({
    'inviteCode' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : IDL.Int,
  });
  const ReferralRewardSummary = IDL.Record({
    'pendingRewards' : IDL.Nat,
    'totalEarned' : IDL.Nat,
    'paidRewards' : IDL.Vec(ReferralRewardRecord),
  });
  const SavingsGoal = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'targetAmount' : IDL.Nat,
    'targetDate' : IDL.Opt(Timestamp),
    'category' : SavingsCategory,
    'isLocked' : IDL.Bool,
    'currentAmount' : IDL.Nat,
    'autoDepositInterval' : IDL.Opt(IDL.Text),
    'autoDepositAmount' : IDL.Opt(IDL.Nat),
  });
  const CategoryBreakdown = IDL.Record({
    'total' : IDL.Nat,
    'count' : IDL.Nat,
    'category' : SpendingCategory,
  });
  const AnalyticsSummary = IDL.Record({
    'totalSpent' : IDL.Nat,
    'avgTransaction' : IDL.Nat,
    'byCategory' : IDL.Vec(CategoryBreakdown),
    'biggestPurchase' : IDL.Nat,
    'monthOverMonth' : IDL.Int,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'trialing' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'status' : SubscriptionStatus,
    'interval' : BillingInterval,
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'tier' : SubscriptionTier,
    'currentPeriodEnd' : IDL.Int,
  });
  const TxType = IDL.Variant({
    'request' : IDL.Null,
    'sent' : IDL.Null,
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'received' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TxId,
    'status' : TxStatus,
    'requestId' : IDL.Opt(TxId),
    'tax_amount' : Amount,
    'original_amount' : IDL.Opt(Amount),
    'note' : IDL.Text,
    'counterparty' : IDL.Opt(IDL.Principal),
    'currency' : Currency,
    'original_currency' : IDL.Opt(Currency),
    'timestamp' : Timestamp,
    'tax_rate' : IDL.Nat,
    'txType' : TxType,
    'base_amount' : Amount,
    'amount' : Amount,
  });
  const TxMetadata = IDL.Record({
    'note' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'txId' : TxId,
  });
  const TrustedContact = IDL.Record({
    'id' : IDL.Nat,
    'accessLevel' : IDL.Text,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'addedAt' : Timestamp,
    'phone' : IDL.Opt(IDL.Text),
  });
  const NumberFormat = IDL.Variant({ 'Period' : IDL.Null, 'Comma' : IDL.Null });
  const TxHistoryVisibility = IDL.Variant({
    'FriendsOnly' : IDL.Null,
    'Private' : IDL.Null,
    'Public' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'primary_currency' : Currency,
    'data_sharing' : IDL.Bool,
    'per_tx_limit' : Amount,
    'decimal_places' : IDL.Nat,
    'notification_promotions' : IDL.Bool,
    'notification_p2p_requests' : IDL.Bool,
    'number_format' : NumberFormat,
    'monthly_limit' : Amount,
    'notification_email_receipts' : IDL.Bool,
    'tx_history_visibility' : TxHistoryVisibility,
    'notification_payment_alerts' : IDL.Bool,
    'daily_limit' : Amount,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptMoneyRequest' : IDL.Func([TxId], [], []),
    'addFunds' : IDL.Func([Amount], [], []),
    'addPaymentMethod' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, PaymentMethodType, IDL.Text],
        [],
        [],
      ),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'addTrustedContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'autoDepositOnReceive' : IDL.Func(
        [TxId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'cancelSubscription' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'chargeCard' : IDL.Func(
        [IDL.Text, Amount, Currency],
        [StripePaymentResult],
        [],
      ),
    'confirmStripePaymentMethod' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PaymentMethodType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [PaymentMethod],
        [],
      ),
    'convertCurrency' : IDL.Func(
        [Amount, Currency, Currency],
        [CurrencyAmount],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInviteCode' : IDL.Func([], [IDL.Text], []),
    'createSavingsGoal' : IDL.Func(
        [IDL.Text, SavingsCategory, IDL.Nat, IDL.Opt(Timestamp)],
        [],
        [],
      ),
    'createStripeSetupIntent' : IDL.Func([], [StripeSetupIntent], []),
    'createSubscriptionCheckout' : IDL.Func(
        [SubscriptionTier, BillingInterval],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'depositToGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'exportTransactionsCsv' : IDL.Func([], [IDL.Text], []),
    'findUser' : IDL.Func(
        [
          IDL.Variant({
            'username' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'findUserByIdOrUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'freezeCard' : IDL.Func([IDL.Text], [], []),
    'fxTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'generateVirtualCard' : IDL.Func([IDL.Text], [CardControl], []),
    'getActivityFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ActivityItem)],
        ['query'],
      ),
    'getAutoPayConfig' : IDL.Func([], [AutoPayConfig], ['query']),
    'getBalance' : IDL.Func([], [Amount], ['query']),
    'getBudgets' : IDL.Func([], [IDL.Vec(BudgetSetting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCardControls' : IDL.Func([IDL.Text], [CardControl], ['query']),
    'getCurrencySymbol' : IDL.Func([Currency], [IDL.Text], ['query']),
    'getDeviceSessions' : IDL.Func([], [IDL.Vec(DeviceSession)], []),
    'getExchangeRate' : IDL.Func([Currency, Currency], [FxRate], []),
    'getInviteCode' : IDL.Func([], [IDL.Text], []),
    'getInviteStats' : IDL.Func([], [InviteStats], ['query']),
    'getMultiCurrencyBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Currency, Amount))],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
    'getReferralRewards' : IDL.Func([], [ReferralRewardSummary], ['query']),
    'getSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
    'getSpendingAnalytics' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [AnalyticsSummary],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Opt(TxType)],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionMetadata' : IDL.Func([TxId], [TxMetadata], ['query']),
    'getTrustedContacts' : IDL.Func([], [IDL.Vec(TrustedContact)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [UserSettings], []),
    'initiateWithdrawal' : IDL.Func(
        [IDL.Text, Amount, Currency],
        [StripePaymentResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isTwilioConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'lockGoal' : IDL.Func([IDL.Nat], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'redeemInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'rejectMoneyRequest' : IDL.Func([TxId], [], []),
    'removePaymentMethod' : IDL.Func([IDL.Nat], [], []),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'removeTrustedContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reportCardLostStolen' : IDL.Func([IDL.Text], [], []),
    'requestMoney' : IDL.Func([IDL.Principal, Amount, IDL.Text], [], []),
    'requestPhoneVerification' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'revokeAllSessions' : IDL.Func([], [], []),
    'revokeDeviceSession' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMoney' : IDL.Func([IDL.Principal, Amount, IDL.Text], [], []),
    'setBudget' : IDL.Func([SpendingCategory, IDL.Nat, IDL.Nat], [], []),
    'setCardControls' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'setDefaultPaymentMethod' : IDL.Func([IDL.Nat], [], []),
    'setGoalAutoDeposit' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([IDL.Text], [], []),
    'setTransactionCategory' : IDL.Func([TxId, SpendingCategory], [], []),
    'setTransactionNote' : IDL.Func([TxId, IDL.Text], [], []),
    'setTransactionTags' : IDL.Func([TxId, IDL.Vec(IDL.Text)], [], []),
    'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'togglePaymentVisibility' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'twilioTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfreezeCard' : IDL.Func([IDL.Text], [], []),
    'unlinkPhone' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateAutoPayConfig' : IDL.Func(
        [AutoPayConfig],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateProfilePhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateTrustedContact' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateUserSettings' : IDL.Func([UserSettings], [], []),
    'upsertSubscription' : IDL.Func([Subscription], [], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'withdrawFromGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'withdrawFunds' : IDL.Func([Amount], [], []),
  });
};

export const init = ({ IDL }) => { return []; };