/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityItem {
  'id' : bigint,
  'note' : [] | [string],
  'actionType' : ActivityType,
  'actorUsername' : string,
  'currency' : [] | [Currency],
  'timestamp' : Timestamp,
  'actorPrincipal' : Principal,
  'isPublic' : boolean,
  'amount' : [] | [bigint],
  'reactions' : Array<ReactionEntry>,
}
export type ActivityType = { 'JoinedViaInvite' : null } |
  { 'Sent' : null } |
  { 'Achievement' : null } |
  { 'Received' : null } |
  { 'SavingsGoal' : null };
export type Amount = bigint;
export interface AnalyticsSummary {
  'totalSpent' : bigint,
  'avgTransaction' : bigint,
  'byCategory' : Array<CategoryBreakdown>,
  'biggestPurchase' : bigint,
  'monthOverMonth' : bigint,
}
export interface AutoPayConfig {
  'defaultPayoutMethodId' : [] | [string],
  'autoDepositOnReceive' : boolean,
  'autoChargeOnSend' : boolean,
}
export type BillingInterval = { 'annual' : null } |
  { 'monthly' : null };
export interface BudgetSetting {
  'limitCents' : bigint,
  'alertThreshold' : bigint,
  'category' : SpendingCategory,
}
export interface CardControl {
  'isFrozen' : boolean,
  'internationalEnabled' : boolean,
  'paymentMethodId' : string,
  'hasVirtualCard' : boolean,
  'onlineEnabled' : boolean,
  'virtualCardLast4' : [] | [string],
  'virtualCardExpiry' : [] | [string],
  'maxTransactionLimit' : [] | [bigint],
}
export interface CategoryBreakdown {
  'total' : bigint,
  'count' : bigint,
  'category' : SpendingCategory,
}
export type Currency = { 'AUD' : null } |
  { 'CAD' : null } |
  { 'EUR' : null } |
  { 'GBP' : null } |
  { 'JPY' : null } |
  { 'USD' : null };
export interface CurrencyAmount { 'currency' : Currency, 'amount' : Amount }
export interface DeviceSession {
  'os' : string,
  'session_id' : string,
  'device_name' : string,
  'last_active' : Timestamp,
  'is_current' : boolean,
  'ip_address' : string,
}
export interface FxRate {
  'rate' : number,
  'to_currency' : Currency,
  'from_currency' : Currency,
  'fetched_at' : Timestamp,
}
export interface InviteStats {
  'redeemerUsernames' : Array<string>,
  'redemptionCount' : bigint,
  'code' : string,
}
export interface MoneyRequest {
  'id' : TxId,
  'status' : TxStatus,
  'requester' : Principal,
  'note' : string,
  'currency' : Currency,
  'timestamp' : Timestamp,
  'payer' : Principal,
  'amount' : Amount,
}
export type NotifType = { 'System' : null } |
  { 'Security' : null } |
  { 'Promo' : null } |
  { 'Alert' : null } |
  { 'Payment' : null };
export interface Notification {
  'id' : bigint,
  'title' : string,
  'notifType' : NotifType,
  'body' : string,
  'isRead' : boolean,
  'timestamp' : Timestamp,
  'relatedTxId' : [] | [TxId],
}
export type NumberFormat = { 'Period' : null } |
  { 'Comma' : null };
export interface PaymentMethod {
  'id' : bigint,
  'token' : string,
  'last4' : string,
  'stripe_payment_method_id' : [] | [string],
  'verification_status' : VerificationStatus,
  'displayLabel' : string,
  'isDefault' : boolean,
  'pmType' : PaymentMethodType,
  'expiry' : string,
  'account_holder_name' : [] | [string],
}
export type PaymentMethodType = { 'bank' : null } |
  { 'card' : null };
export interface ReactionEntry { 'by' : Array<Principal>, 'emoji' : string }
export interface ReferralRewardRecord {
  'inviteCode' : string,
  'amount' : bigint,
  'paidAt' : bigint,
}
export interface ReferralRewardSummary {
  'pendingRewards' : bigint,
  'totalEarned' : bigint,
  'paidRewards' : Array<ReferralRewardRecord>,
}
export type SavingsCategory = { 'Car' : null } |
  { 'Home' : null } |
  { 'Custom' : null } |
  { 'Vacation' : null } |
  { 'Emergency' : null };
export interface SavingsGoal {
  'id' : bigint,
  'isCompleted' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'targetAmount' : bigint,
  'targetDate' : [] | [Timestamp],
  'category' : SavingsCategory,
  'isLocked' : boolean,
  'currentAmount' : bigint,
  'autoDepositInterval' : [] | [string],
  'autoDepositAmount' : [] | [bigint],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SpendingCategory = { 'Food' : null } |
  { 'Bills' : null } |
  { 'Entertainment' : null } |
  { 'Shopping' : null } |
  { 'Other' : null } |
  { 'Transfers' : null } |
  { 'Transport' : null };
export interface StripePaymentResult {
  'amount_charged' : Amount,
  'error_message' : [] | [string],
  'currency' : Currency,
  'charge_id' : [] | [string],
  'success' : boolean,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StripeSetupIntent {
  'payment_method_id' : [] | [string],
  'client_secret' : string,
}
export interface Subscription {
  'status' : SubscriptionStatus,
  'interval' : BillingInterval,
  'stripeSubscriptionId' : [] | [string],
  'tier' : SubscriptionTier,
  'currentPeriodEnd' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'trialing' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'free' : null } |
  { 'plus' : null } |
  { 'business' : null };
export type Timestamp = bigint;
export interface Transaction {
  'id' : TxId,
  'status' : TxStatus,
  'requestId' : [] | [TxId],
  'tax_amount' : Amount,
  'original_amount' : [] | [Amount],
  'note' : string,
  'counterparty' : [] | [Principal],
  'currency' : Currency,
  'original_currency' : [] | [Currency],
  'timestamp' : Timestamp,
  'tax_rate' : bigint,
  'txType' : TxType,
  'base_amount' : Amount,
  'amount' : Amount,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrustedContact {
  'id' : bigint,
  'accessLevel' : string,
  'relationship' : string,
  'name' : string,
  'email' : [] | [string],
  'addedAt' : Timestamp,
  'phone' : [] | [string],
}
export type TxHistoryVisibility = { 'FriendsOnly' : null } |
  { 'Private' : null } |
  { 'Public' : null };
export type TxId = bigint;
export interface TxMetadata {
  'note' : [] | [string],
  'tags' : Array<string>,
  'txId' : TxId,
}
export type TxStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export type TxType = { 'request' : null } |
  { 'sent' : null } |
  { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'received' : null };
export interface UserProfile {
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
  'userId' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'primary_currency' : Currency,
  'data_sharing' : boolean,
  'per_tx_limit' : Amount,
  'decimal_places' : bigint,
  'notification_promotions' : boolean,
  'notification_p2p_requests' : boolean,
  'number_format' : NumberFormat,
  'monthly_limit' : Amount,
  'notification_email_receipts' : boolean,
  'tx_history_visibility' : TxHistoryVisibility,
  'notification_payment_alerts' : boolean,
  'daily_limit' : Amount,
}
export type VerificationStatus = { 'Failed' : null } |
  { 'Unverified' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptMoneyRequest' : ActorMethod<[TxId], undefined>,
  'addFunds' : ActorMethod<[Amount], undefined>,
  'addPaymentMethod' : ActorMethod<
    [string, string, string, PaymentMethodType, string],
    undefined
  >,
  'addReaction' : ActorMethod<[bigint, string], boolean>,
  'addTrustedContact' : ActorMethod<
    [string, string, [] | [string], [] | [string], string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autoDepositOnReceive' : ActorMethod<
    [TxId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'cancelSubscription' : ActorMethod<
    [],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'chargeCard' : ActorMethod<[string, Amount, Currency], StripePaymentResult>,
  'confirmStripePaymentMethod' : ActorMethod<
    [string, string, PaymentMethodType, string, string, [] | [string]],
    PaymentMethod
  >,
  'convertCurrency' : ActorMethod<[Amount, Currency, Currency], CurrencyAmount>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInviteCode' : ActorMethod<[], string>,
  'createSavingsGoal' : ActorMethod<
    [string, SavingsCategory, bigint, [] | [Timestamp]],
    undefined
  >,
  'createStripeSetupIntent' : ActorMethod<[], StripeSetupIntent>,
  'createSubscriptionCheckout' : ActorMethod<
    [SubscriptionTier, BillingInterval],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'depositToGoal' : ActorMethod<[bigint, bigint], undefined>,
  'exportTransactionsCsv' : ActorMethod<[], string>,
  'findUser' : ActorMethod<
    [{ 'username' : string } | { 'email' : string } | { 'phone' : string }],
    [] | [Principal]
  >,
  'findUserByIdOrUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'freezeCard' : ActorMethod<[string], undefined>,
  'fxTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'generateVirtualCard' : ActorMethod<[string], CardControl>,
  'getActivityFeed' : ActorMethod<[bigint, bigint], Array<ActivityItem>>,
  'getAutoPayConfig' : ActorMethod<[], AutoPayConfig>,
  'getBalance' : ActorMethod<[], Amount>,
  'getBudgets' : ActorMethod<[], Array<BudgetSetting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCardControls' : ActorMethod<[string], CardControl>,
  'getCurrencySymbol' : ActorMethod<[Currency], string>,
  'getDeviceSessions' : ActorMethod<[], Array<DeviceSession>>,
  'getExchangeRate' : ActorMethod<[Currency, Currency], FxRate>,
  'getInviteCode' : ActorMethod<[], string>,
  'getInviteStats' : ActorMethod<[], InviteStats>,
  'getMultiCurrencyBalances' : ActorMethod<[], Array<[Currency, Amount]>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingRequests' : ActorMethod<[], Array<MoneyRequest>>,
  'getReferralRewards' : ActorMethod<[], ReferralRewardSummary>,
  'getSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getSpendingAnalytics' : ActorMethod<[bigint, bigint], AnalyticsSummary>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getTransactionHistory' : ActorMethod<[[] | [TxType]], Array<Transaction>>,
  'getTransactionMetadata' : ActorMethod<[TxId], TxMetadata>,
  'getTrustedContacts' : ActorMethod<[], Array<TrustedContact>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'initiateWithdrawal' : ActorMethod<
    [string, Amount, Currency],
    StripePaymentResult
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isTwilioConfigured' : ActorMethod<[], boolean>,
  'listPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'lockGoal' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'redeemInviteCode' : ActorMethod<[string], boolean>,
  'rejectMoneyRequest' : ActorMethod<[TxId], undefined>,
  'removePaymentMethod' : ActorMethod<[bigint], undefined>,
  'removeReaction' : ActorMethod<[bigint, string], boolean>,
  'removeTrustedContact' : ActorMethod<[bigint], boolean>,
  'reportCardLostStolen' : ActorMethod<[string], undefined>,
  'requestMoney' : ActorMethod<[Principal, Amount, string], undefined>,
  'requestPhoneVerification' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'revokeAllSessions' : ActorMethod<[], undefined>,
  'revokeDeviceSession' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMoney' : ActorMethod<[Principal, Amount, string], undefined>,
  'setBudget' : ActorMethod<[SpendingCategory, bigint, bigint], undefined>,
  'setCardControls' : ActorMethod<
    [string, boolean, boolean, [] | [bigint]],
    undefined
  >,
  'setDefaultPaymentMethod' : ActorMethod<[bigint], undefined>,
  'setGoalAutoDeposit' : ActorMethod<[bigint, bigint, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[string], undefined>,
  'setTransactionCategory' : ActorMethod<[TxId, SpendingCategory], undefined>,
  'setTransactionNote' : ActorMethod<[TxId, string], undefined>,
  'setTransactionTags' : ActorMethod<[TxId, Array<string>], undefined>,
  'setTwilioConfig' : ActorMethod<[string, string, string], undefined>,
  'togglePaymentVisibility' : ActorMethod<[bigint, boolean], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'twilioTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfreezeCard' : ActorMethod<[string], undefined>,
  'unlinkPhone' : ActorMethod<[], { 'ok' : boolean } | { 'err' : string }>,
  'updateAutoPayConfig' : ActorMethod<
    [AutoPayConfig],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateProfilePhoto' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateTrustedContact' : ActorMethod<
    [bigint, string, string, [] | [string], [] | [string], string],
    boolean
  >,
  'updateUserSettings' : ActorMethod<[UserSettings], undefined>,
  'upsertSubscription' : ActorMethod<[Subscription], undefined>,
  'validateInviteCode' : ActorMethod<[string], boolean>,
  'verifyPhone' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'withdrawFromGoal' : ActorMethod<[bigint, bigint], undefined>,
  'withdrawFunds' : ActorMethod<[Amount], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];